services:
  data-loader:
    build: data-loader/.
    volumes:
      - ./data-loader/apps:/apps
      - ./data:/data
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      internal:
        ipv4_address: 172.18.0.4
  web-server:
    build: web-server/.
    restart: always
    volumes:
      - ./web-server/app:/app
      - ./data:/data
      - ./network-configuration:/network-configuration
    depens_on:
      data-loader:
        condition: service_completed_successfully
    networks:
      internal:
        ipv4_address: 172.18.0.2
  variant-server:
    build: variant-server/.
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./variant-server/app:/app
    depens_on:
      data-loader:
        condition: service_completed_successfully
    networks:
      internal:
        ipv4_address: 172.18.0.3
  mariadb:
    build: mariadb/.
    restart: always
    command: --max_allowed_packet=1073741824
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./data/mariadb-data:/var/lib/mysql
      - ./mariadb/schema-mariadb.sql:/docker-entrypoint-initdb.d/schema-mariadb.sql
    depens_on:
      data-loader:
        condition: service_completed_successfully
    networks:
      internal:
        ipv4_address: 172.18.0.5
  nginx:
    build: nginx/.
    restart: always
    depens_on:
      data-loader:
        condition: service_completed_successfully
      web-server:
      variant-server:
    volumes:
      - ./nginx/server-certificates:/server-certificates
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./network-configuration:/network-configuration
    ports: 
      - 80:80
      - 443:443
      - 5000:5000
    networks:
      internal:
        ipv4_address: 172.18.0.6
networks:
  internal:
    ipam:
      config:
        - subnet: 172.18.0.0/16